### ISSUE TITLE
Organização de nomes e diretórios dos componentes

### ISSUE THREAD

**Issue by davidedup** [paulojuniore/MinhasSeries-DevWeb#10]
Percebi que tu ta separando teu componentes em pastas e todo arquivo se chama index.js. Acho que dessa forma não é uma boa pratica, talvez depois fique bem difícil tu achar teu componentes e fica difícil a manutenção do código.

Eu vou explicar como eu faço no meu, mas tu pode procurar na internet as melhores praticas nesses sentido. 

Eu uso as pastas pra dividir os componentes de acordo com o contexto, por exemplo, componentes da pagina inicial ficariam em uma pasta chamada /home, já componentes da pagina de sobre ficaria na pasta /sobre. E dentro de cada uma dessas pastas estariam os componentes som seus nomes. Por exemplo, em /sobre poderia ter   um componente chamado contado.js, quadroDaEsquipe.js e etc

**Comment by paulojuniore** [comment]
Eu utilizo essa abordagem porque é mais simples de você identificar o componente através do nome da pasta, e dentro dela haverá o seu index.js e o styles.css, apenas. E na hora do import eu preciso apenas colocar o caminho até a pasta, pois o node já busca pelo arquivo de nome index.js naquela pasta especificada. E eu também utilizo a pasta pages que organiza os componente para cada tela (também em pastas), então elimina essa necessidade de organização. Mas mesmo assim, obrigado pela sugestão. Irei pesquisar sobre.
