### ISSUE TITLE
Formas de não validar entradas indevidas

### ISSUE THREAD

**Issue by JonathanAllisson** [paulojuniore/MinhasSeries-DevWeb#11]
Seria interessante pra aplicação validar ou não a forma de criar gêneros ou séries, aqui consegui criar um gênero com nome vazio.

**Comment by paulojuniore** [comment]
Massa, já estava pensando nisso. Irei iniciar nessa parte assim que a funcionalidade principal esteja ok. Obrigado pela sugestão, @JonathanAllisson.

**Comment by paulojuniore** [comment]
Closed on commit https://github.com/paulojuniore/MinhasSeries-DevWeb/commit/a1a16d0512c5b94f448dc5ad90968283da3cfdd0
