### ISSUE TITLE
Quebrar em componentes menores

### ISSUE THREAD

**Issue by matheusgr** [paulojuniore/MinhasSeries-DevWeb#21]
https://github.com/paulojuniore/MinhasSeries-DevWeb/blob/119100b4fb8c35306d3a849ec11a19ff00084793/frontend/src/components/GeneralListComponent/index.js#L60-L121

**Comment by paulojuniore** [comment]
O Sr. poderia me dar uma luz de como e em quais componentes dividir? Pois como forma de abstração eu tentei fazer um único componente, no caso o GeneralListComponent, que lista séries e gêneros, pelo fato de as duas telas terem a estrutura muito semelhante, o que mais diferencia na estrutura é apenas a quantidade de colunas que a tabelas de séries e gêneros possuem.

**Comment by paulojuniore** [comment]
Ok, professor. Criei dois novos componentes para "enxugar" essa parte da renderização condicional.
