### ISSUE TITLE
Organização do back-end

### ISSUE THREAD

**Issue by higorsnt** [paulojuniore/MinhasSeries-DevWeb#24]
Os controllers estão com algumas regras de serviço que acredito que já deveria estar em uma camada de service, para até facilitar manutenção e leitura

**Comment by paulojuniore** [comment]
Não entendi bem, @HigorSnt. Você poderia ser mais específico utilizando de um exemplo?

**Comment by higorsnt** [comment]
Falo em relação, principalmente ao SeriesController, à quantidade de consultas ao banco e de regras de negócio presentes, como o exemplo que destaco abaixo. Daí, acredito que o ideal seria separar o Controller para receber e responder às requisições e um Service para realizar tais ações mais específicas.

Mas, é apenas uma ideia de modularização de modo a facilitar futuras manutenções... 😄 

https://github.com/paulojuniore/MinhasSeries-DevWeb/blob/177eb034aa974fe790fb0a6a350531e658ee9f66/backend/src/controller/SeriesController.js#L15-L27
