### ISSUE TITLE
Colocar status http nas rotas

### ISSUE THREAD

**Issue by davidedup** [paulojuniore/MinhasSeries-DevWeb#7]
Acho que é interessante no final de todas as rotas você ter um http status, não apenas nas que dão erro. 

Por exemplo, quando der certo o get de genres fazer:

`` res.status("200"); ``

**Comment by paulojuniore** [comment]
Massa @davidedup, obrigado pela sugestão! Assim irei fazer!

**Comment by paulojuniore** [comment]
Closed on commit https://github.com/paulojuniore/MinhasSeries-DevWeb/commit/e39c6cf783088967f2f158b985357ae60056e659
