### ISSUE TITLE
Remover pastas desnecessárias

### ISSUE THREAD

**Issue by vitoria** [paulojuniore/MinhasSeries-DevWeb#8]
Para um componente, você só precisa criar uma pasta para ele, se for ter mais de um arquivo dentro da pasta, além do `index.js`.

Como está:
```
src
 - components
-- NewSerie
--- index.js
...
```

Como ficaria melhor:
```
src
 - components
-- NewSerie.js
...
```

**Comment by paulojuniore** [comment]
Logo logo eu irei criar os arquivos .css para cada componente para separar a estilização, já que no momento eu estou fazendo no próprio arquivo .js, atráves da propriedade style.
