### ISSUE TITLE
Criar funções no serviço de API para deixar as requisições nos componentes mais simples

### ISSUE THREAD

**Issue by vitoria** [paulojuniore/MinhasSeries-DevWeb#9]
No seu módulo de serviço API, você poderia criar métodos para abstrair as requisições, como `createGender` e `createSerie`, assim você reune todas as chamadas de api em um lugar só e fica mais fácil para alterar e também mais fácil para os componentes usar, já que eles não vão precisar saber o `endpoint` daquela requisições, por exemplo, precisando passar apenas os parâmetros e/ou corpo da requisição. 😄

**Comment by paulojuniore** [comment]
É verdade! Obrigado pela sugestão, @vitoria. Irei implementar! :)
